### ISSUE TITLE
ViewScope not serializable

### ISSUE THREAD

**Issue by mikedehaan** [javaplugs/spring-jsf#6]
ViewScope uses WeakHashMap which is not serializable.

<code>
WARNING: Cannot serialize session attribute sessionBindingListener for session 34C7AF60639529F149057068DC5B7B44
java.io.NotSerializableException: java.util.WeakHashMap
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1700)
	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1092)
	at org.apache.catalina.session.JDBCStore.save(JDBCStore.java:836)
	at org.apache.catalina.valves.PersistentValve.invoke(PersistentValve.java:187)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)
</code>

**Comment by rumatoest** [comment]
But we do not want to save view beans. 
We must drop them as long as they became useless.

**Comment by mikedehaan** [comment]
Then there are two choices:

1) Remove the Serializable interface from the ViewScope class (as it is not currently Serializable)
2) Fix the class so it is Serializable and doesn't break non-sticky session applications

**Comment by rumatoest** [comment]
Ok there is a version 1.1.2 without Serializable interface. You could check it.
